In [1]:
import pandas as pd
import numpy as np

In [13]:
# taken from last version
counties_more_df = pd.DataFrame([
[   1,"Beaver"              ,"Rural","0 - UDOT (Rural)"  ],
[   3,"Box Elder"           ,"Rural","0 - UDOT (Rural)"  ],
[   5,"Cache"               ,"Urban","2 - Cache"         ],
[   7,"Carbon"              ,"Rural","0 - UDOT (Rural)"  ],
[   9,"Daggett"             ,"Rural","0 - UDOT (Rural)"  ],
[  11,"Davis"               ,"Urban","1 - Wasatch Front" ],
[  13,"Duchesne"            ,"Rural","0 - UDOT (Rural)"  ],
[  15,"Emery"               ,"Rural","0 - UDOT (Rural)"  ],
[  17,"Garfield"            ,"Rural","0 - UDOT (Rural)"  ],
[  19,"Grand"               ,"Rural","0 - UDOT (Rural)"  ],
[  21,"Iron"                ,"Rural","5 - Iron"          ],
[  23,"Juab"                ,"Rural","0 - UDOT (Rural)"  ],
[  25,"Kane"                ,"Rural","0 - UDOT (Rural)"  ],
[  27,"Millard"             ,"Rural","0 - UDOT (Rural)"  ],
[  29,"Morgan"              ,"Rural","0 - UDOT (Rural)"  ],
[  31,"Piute"               ,"Rural","0 - UDOT (Rural)"  ],
[  33,"Rich"                ,"Rural","0 - UDOT (Rural)"  ],
[  35,"Salt Lake"           ,"Urban","1 - Wasatch Front" ],
[  37,"San Juan"            ,"Rural","0 - UDOT (Rural)"  ],
[  39,"Sanpete"             ,"Rural","0 - UDOT (Rural)"  ],
[  41,"Sevier"              ,"Rural","0 - UDOT (Rural)"  ],
[  43,"Summit"              ,"Rural","4 - Summit-Wasatch"],
[  45,"Tooele"              ,"Rural","0 - UDOT (Rural)"  ],
[  47,"Uintah"              ,"Rural","0 - UDOT (Rural)"  ],
[  49,"Utah"                ,"Urban","1 - Wasatch Front" ],
[  51,"Wasatch"             ,"Rural","4 - Summit-Wasatch"],
[  53,"Washington"          ,"Urban","3 - Dixie"         ],
[  55,"Wayne"               ,"Rural","0 - UDOT (Rural)"  ],
[  57,"Weber"               ,"Urban","1 - Wasatch Front" ],
[1003,"Box Elder - Rural"   ,"Rural","0 - UDOT (Rural)"  ],
[1049,"State of Utah"       ,"State","6 - State"         ],
[1103,"Box Elder - Urban"   ,"Urban","1 - Wasatch Front" ],
[9057,"Weber - Ogden Valley","Rural","0 - UDOT (Rural)"  ],
[9157,"Weber - WFRC"        ,"Urban","1 - Wasatch Front" ]
],columns=["CO_FIPS","CO_NAME","Urban_Rural","Subarea"])

counties_more_df['CO_NAME'] = counties_more_df["CO_NAME"].str.upper()

counties_more_df

    CO_FIPS               CO_NAME Urban_Rural             Subarea
0         1                BEAVER       Rural    0 - UDOT (Rural)
1         3             BOX ELDER       Rural    0 - UDOT (Rural)
2         5                 CACHE       Urban           2 - Cache
3         7                CARBON       Rural    0 - UDOT (Rural)
4         9               DAGGETT       Rural    0 - UDOT (Rural)
5        11                 DAVIS       Urban   1 - Wasatch Front
6        13              DUCHESNE       Rural    0 - UDOT (Rural)
7        15                 EMERY       Rural    0 - UDOT (Rural)
8        17              GARFIELD       Rural    0 - UDOT (Rural)
9        19                 GRAND       Rural    0 - UDOT (Rural)
10       21                  IRON       Rural            5 - Iron
11       23                  JUAB       Rural    0 - UDOT (Rural)
12       25                  KANE       Rural    0 - UDOT (Rural)
13       27               MILLARD       Rural    0 - UDOT (Rural)
14       29                MORGAN       Rural    0 - UDOT (Rural)
15       31                 PIUTE       Rural    0 - UDOT (Rural)
16       33                  RICH       Rural    0 - UDOT (Rural)
17       35             SALT LAKE       Urban   1 - Wasatch Front
18       37              SAN JUAN       Rural    0 - UDOT (Rural)
19       39               SANPETE       Rural    0 - UDOT (Rural)
20       41                SEVIER       Rural    0 - UDOT (Rural)
21       43                SUMMIT       Rural  4 - Summit-Wasatch
22       45                TOOELE       Rural    0 - UDOT (Rural)
23       47                UINTAH       Rural    0 - UDOT (Rural)
24       49                  UTAH       Urban   1 - Wasatch Front
25       51               WASATCH       Rural  4 - Summit-Wasatch
26       53            WASHINGTON       Urban           3 - Dixie
27       55                 WAYNE       Rural    0 - UDOT (Rural)
28       57                 WEBER       Urban   1 - Wasatch Front
29     1003     BOX ELDER - RURAL       Rural    0 - UDOT (Rural)
30     1049         STATE OF UTAH       State           6 - State
31     1103     BOX ELDER - URBAN       Urban   1 - Wasatch Front
32     9057  WEBER - OGDEN VALLEY       Rural    0 - UDOT (Rural)
33     9157          WEBER - WFRC       Urban   1 - Wasatch Front

In [2]:
se_df = pd.concat([pd.read_csv('intermediate/split_emp.csv'), pd.read_csv('intermediate/split_pop.csv')])
se_df

      CO_FIPS  YEAR VARIABLE   VALUE
0           1  2023     AGRI     730
1           1  2023     CONS     264
2           1  2023     FOOD     511
3           1  2023     GVED     750
4           1  2023      HBJ     244
...       ...   ...      ...     ...
9109     9157  2065    HHPOP  367411
9110     9157  2065       HH  164591
9111     9157  2065  POP0017   59084
9112     9157  2065  POP1864  222289
9113     9157  2065   POP65P   91658

[9482 rows x 4 columns]

In [3]:
se_df[(se_df['YEAR']==2023) & (se_df['VARIABLE']=='HH')]

      CO_FIPS  YEAR VARIABLE   VALUE
6           1  2023       HH    2280
300         5  2023       HH   44622
594         7  2023       HH    7861
888         9  2023       HH     405
1182       11  2023       HH  120087
1476       13  2023       HH    6560
1770       15  2023       HH    3756
2064       17  2023       HH    1877
2358       19  2023       HH    3984
2652       21  2023       HH   21467
2946       23  2023       HH    3975
3240       25  2023       HH    3104
3534       27  2023       HH    4370
3828       29  2023       HH    4211
4122       31  2023       HH     605
4416       33  2023       HH     958
4710       35  2023       HH  428373
5004       37  2023       HH    5167
5298       39  2023       HH    9226
5592       41  2023       HH    7586
5886       43  2023       HH   14382
6180       45  2023       HH   24833
6474       47  2023       HH   12148
6768       49  2023       HH  211379
7062       51  2023       HH   12556
7356       53  2023       HH   70844
7650       55  2023       HH     947
7944     9003  2023       HH    9191
8238     9057  2023       HH    3212
8532     9103  2023       HH   10833
8826     9157  2023       HH   91269

In [4]:
se_pivot_df = se_df.pivot(index=['CO_FIPS','YEAR'],columns='VARIABLE',values='VALUE').reset_index().fillna(0).astype(int)
se_pivot_df

VARIABLE,CO_FIPS,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1,2023,730,264,511,299,750,244,2280,7015,...,194,101,129,906,1942,4239,1133,485,7314,266
1,1,2025,0,0,0,369,0,0,2472,7163,...,0,0,0,0,2071,4310,1152,0,7533,0
2,1,2026,0,0,0,351,0,0,2516,7226,...,0,0,0,0,2030,4353,1194,0,7577,0
3,1,2027,0,0,0,295,0,0,2561,7287,...,0,0,0,0,1996,4363,1223,0,7582,0
4,1,2028,0,0,0,303,0,0,2600,7331,...,0,0,0,0,1971,4386,1277,0,7634,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,9157,2061,0,0,0,5406,0,0,157287,356144,...,0,0,0,0,59730,216417,85404,0,361551,0
1300,9157,2062,0,0,0,5460,0,0,159127,358961,...,0,0,0,0,59495,217801,87125,0,364421,0
1301,9157,2063,0,0,0,5513,0,0,160960,361776,...,0,0,0,0,59303,219248,88737,0,367288,0
1302,9157,2064,0,0,0,5567,0,0,162781,364591,...,0,0,0,0,59165,220852,90141,0,370158,0
1303,9157,2065,0,0,0,5622,0,0,164591,367411,...,0,0,0,0,59084,222289,91658,0,373033,0

In [10]:
# add a state total grouping

# add a state with CO_FIPS 1049
# Identify numeric columns except keys
value_cols = [
    c for c in se_pivot_df.columns
    if c not in ["CO_FIPS", "YEAR"]
]

# Compute statewide totals by YEAR
utah_totals_df = (
    se_pivot_df
      .groupby("YEAR")[value_cols]
      .sum()
      .reset_index()
)

# Add state-level FIPS
utah_totals_df["CO_FIPS"] = 1049    # 

# Optional: reorder columns
utah_totals_df = utah_totals_df[["CO_FIPS", "YEAR"] + value_cols]
utah_totals_df

VARIABLE,CO_FIPS,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1049,2023,25118,166800,151160,56815,355458,71741,1142068,3399632,...,158910,14470,272270,607024,853666,2156409,446372,228998,3456447,175416
1,1049,2025,0,0,0,58695,0,0,1230457,3497694,...,0,0,0,0,912478,2191079,452838,0,3556391,0
2,1049,2026,0,0,0,60108,0,0,1259651,3544906,...,0,0,0,0,898954,2234608,471448,0,3605012,0
3,1049,2027,0,0,0,61537,0,0,1289257,3592066,...,0,0,0,0,887047,2276832,489724,0,3653603,0
4,1049,2028,0,0,0,61833,0,0,1318888,3638886,...,0,0,0,0,876667,2316979,507064,0,3700715,0
5,1049,2029,0,0,0,61582,0,0,1348197,3684994,...,0,0,0,0,868734,2354605,523235,0,3746574,0
6,1049,2030,0,0,0,61154,0,0,1376961,3730335,...,0,0,0,0,862599,2390799,538098,0,3791492,0
7,1049,2031,0,0,0,61523,0,0,1405063,3774853,...,0,0,0,0,856990,2427523,551866,0,3836376,0
8,1049,2032,0,0,0,61939,0,0,1432438,3818653,...,0,0,0,0,852534,2462494,565573,0,3880591,0
9,1049,2033,0,0,0,62336,0,0,1459080,3861957,...,0,0,0,0,849402,2495645,579244,0,3924295,0
10,1049,2034,0,0,0,62678,0,0,1485017,3904898,...,0,0,0,0,848187,2525437,593955,0,3967570,0
11,1049,2035,0,0,0,62905,0,0,1510407,3947818,...,0,0,0,0,849710,2550971,610042,0,4010719,0
12,1049,2036,0,0,0,63124,0,0,1535633,3991355,...,0,0,0,0,853492,2573478,627510,0,4054478,0
13,1049,2037,0,0,0,63405,0,0,1561239,4036976,...,0,0,0,0,858762,2597571,644043,0,4100383,0
14,1049,2038,0,0,0,63866,0,0,1587458,4085059,...,0,0,0,0,864692,2624018,660220,0,4148922,0
15,1049,2039,0,0,0,64393,0,0,1614117,4135036,...,0,0,0,0,872243,2649847,677337,0,4199429,0
16,1049,2040,0,0,0,64897,0,0,1640766,4185734,...,0,0,0,0,879721,2674627,696284,0,4250631,0
17,1049,2041,0,0,0,65423,0,0,1667184,4236398,...,0,0,0,0,888225,2696950,716652,0,4301819,0
18,1049,2042,0,0,0,65956,0,0,1693366,4286963,...,0,0,0,0,896793,2716252,739873,0,4352916,0
19,1049,2043,0,0,0,66428,0,0,1719470,4337874,...,0,0,0,0,907062,2732790,764443,0,4404303,0
20,1049,2044,0,0,0,66899,0,0,1745719,4389546,...,0,0,0,0,917872,2748701,789865,0,4456445,0
21,1049,2045,0,0,0,67478,0,0,1772333,4442439,...,0,0,0,0,928694,2764743,816479,0,4509918,0
22,1049,2046,0,0,0,68264,0,0,1799492,4496739,...,0,0,0,0,939029,2782941,843036,0,4565001,0
23,1049,2047,0,0,0,69145,0,0,1827331,4552454,...,0,0,0,0,948386,2803426,869788,0,4621600,0
24,1049,2048,0,0,0,70164,0,0,1855669,4609112,...,0,0,0,0,956412,2826949,895920,0,4679278,0
25,1049,2049,0,0,0,71300,0,0,1884333,4666025,...,0,0,0,0,962753,2854489,920074,0,4737324,0
26,1049,2050,0,0,0,72524,0,0,1913066,4722263,...,0,0,0,0,967120,2884290,943377,0,4794788,0
27,1049,2051,0,0,0,73798,0,0,1941599,4777119,...,0,0,0,0,969461,2916367,965087,0,4850917,0
28,1049,2052,0,0,0,75056,0,0,1969857,4830363,...,0,0,0,0,969967,2949895,985552,0,4905419,0
29,1049,2053,0,0,0,76266,0,0,1997949,4882273,...,0,0,0,0,969065,2983007,1006470,0,4958540,0
30,1049,2054,0,0,0,77391,0,0,2025993,4933209,...,0,0,0,0,967375,3014780,1028451,0,5010597,0
31,1049,2055,0,0,0,78425,0,0,2054082,4983380,...,0,0,0,0,965121,3044774,1051913,0,5061802,0
32,1049,2056,0,0,0,79409,0,0,2082123,5032743,...,0,0,0,0,962569,3072668,1076922,0,5112155,0
33,1049,2057,0,0,0,80343,0,0,2110026,5081290,...,0,0,0,0,959963,3099491,1102181,0,5161637,0
34,1049,2058,0,0,0,81200,0,0,2137878,5129277,...,0,0,0,0,957510,3126088,1126884,0,5210479,0
35,1049,2059,0,0,0,82008,0,0,2165766,5177101,...,0,0,0,0,955460,3153479,1150172,0,5259109,0
36,1049,2060,0,0,0,82784,0,0,2193770,5224962,...,0,0,0,0,953953,3179611,1174180,0,5307747,0
37,1049,2061,0,0,0,83532,0,0,2221786,5272840,...,0,0,0,0,953146,3203803,1199427,0,5356372,0
38,1049,2062,0,0,0,84252,0,0,2249736,5320694,...,0,0,0,0,953114,3224579,1227248,0,5404943,0
39,1049,2063,0,0,0,84946,0,0,2277561,5368530,...,0,0,0,0,953914,3245156,1254407,0,5453475,0
40,1049,2064,0,0,0,85665,0,0,2305212,5416327,...,0,0,0,0,955581,3267062,1279346,0,5501990,0
41,1049,2065,0,0,0,86434,0,0,2332663,5464090,...,0,0,0,0,958119,3285334,1307065,0,5550524,0

In [17]:
se_final_df = pd.concat([se_pivot_df,utah_totals_df]).copy()

se_final_df[';INDEX'] = se_final_df['CO_FIPS'].astype(str) + se_final_df['YEAR'].astype(str)
se_final_df[';INDEX'] = se_final_df[';INDEX'].astype(int)

se_final_df['HHSIZE'] = se_final_df['HHPOP'] / se_final_df['HH']
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].replace([np.inf, -np.inf], 0)
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].fillna(0).round(2)

se_final_df['ALLEMP'] = se_final_df['FOOD'] + se_final_df['MANU'] + se_final_df['WSLE'] + se_final_df['OFFI'] + se_final_df['GVED'] + se_final_df['HLTH'] + se_final_df['OTHR'] + se_final_df['AGRI'] + se_final_df['MING'] + se_final_df['CONS'] + se_final_df['HBJ']

se_final_df = se_final_df[[';INDEX','CO_FIPS','YEAR','TOTPOP','GQPOP','HHPOP','HH','HHSIZE','POP0017','POP1864','POP65P','ALLEMP','RETL','FOOD','MANU','WSLE','OFFI','GVED','HLTH','OTHR','AGRI','MING','CONS','HBJ']]

# add extra columns
se_final_df['Job_HH'] = np.round(se_final_df['ALLEMP'] / se_final_df['HH'],2)
se_final_df['WrkPop_Job'] = np.round(se_final_df['POP1864'] / se_final_df['ALLEMP'],2)

se_final_df = se_final_df.merge(counties_more_df, on='CO_FIPS').sort_values([';INDEX'])

se_final_df

,;INDEX,CO_FIPS,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,299,7015,2280,3.08,1942,4239,...,906,730,101,264,244,1.86,1.0,BEAVER,Rural,0 - UDOT (Rural)
1,12025,1,2025,7533,369,7163,2472,2.90,2071,4310,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
2,12026,1,2026,7577,351,7226,2516,2.87,2030,4353,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
3,12027,1,2027,7582,295,7287,2561,2.85,1996,4363,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
4,12028,1,2028,7634,303,7331,2600,2.82,1971,4386,...,0,0,0,0,0,0.00,inf,BEAVER,Rural,0 - UDOT (Rural)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,91572061,9157,2061,361551,5406,356144,157287,2.26,59730,216417,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1216,91572062,9157,2062,364421,5460,358961,159127,2.26,59495,217801,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1217,91572063,9157,2063,367288,5513,361776,160960,2.25,59303,219248,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1218,91572064,9157,2064,370158,5567,364591,162781,2.24,59165,220852,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front
1219,91572065,9157,2065,373033,5622,367411,164591,2.23,59084,222289,...,0,0,0,0,0,0.00,inf,WEBER - WFRC,Urban,1 - Wasatch Front

# Export final table

In [21]:
# Final columns
# ;Index,CO_FIPS,YEAR,TOTPOP,GQ_Pop,HH_Pop,HH,HH_Size,POP_00_17,POP_18_64,POP_65P,ALLEMP,RETL,FOOD,MANU,WSLE,OFFI,GVED,HLTH,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea

# EXPORT ONLY 2023 - FOR NOW
se_final_df[se_final_df['YEAR']==2023].to_csv('results/ControlTotal_SE_AllCounties.csv', index=False)
se_final_df[se_final_df['YEAR']==2023]

,;INDEX,CO_FIPS,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,OTHR,AGRI,MING,CONS,HBJ,Job_HH,WrkPop_Job,CO_NAME,Urban_Rural,Subarea
0,12023,1,2023,7314,299,7015,2280,3.08,1942,4239,...,906,730,101,264,244,1.86,1.00,BEAVER,Rural,0 - UDOT (Rural)
42,32023,3,2023,0,0,0,0,0.00,0,0,...,0,1579,82,2678,190,inf,0.00,BOX ELDER,Rural,0 - UDOT (Rural)
43,52023,5,2023,141700,4467,137233,44622,3.08,35465,90994,...,19766,1829,153,4485,2518,1.85,1.10,CACHE,Urban,2 - Cache
85,72023,7,2023,20654,116,20538,7861,2.61,4829,11702,...,2458,426,632,513,155,1.34,1.11,CARBON,Rural,0 - UDOT (Rural)
127,92023,9,2023,998,0,998,405,2.46,181,532,...,98,67,2,13,13,1.43,0.92,DAGGETT,Rural,0 - UDOT (Rural)
169,112023,11,2023,377378,2429,374949,120087,3.12,101351,229841,...,57704,853,328,14921,5888,1.66,1.15,DAVIS,Urban,1 - Wasatch Front
211,132023,13,2023,20112,87,20025,6560,3.05,5844,11414,...,2117,1271,1878,676,451,1.82,0.96,DUCHESNE,Rural,0 - UDOT (Rural)
253,152023,15,2023,10035,58,9977,3756,2.66,2407,5675,...,982,587,407,695,99,1.32,1.14,EMERY,Rural,0 - UDOT (Rural)
295,172023,17,2023,5141,204,4937,1877,2.63,1043,2746,...,513,285,13,161,121,1.80,0.81,GARFIELD,Rural,0 - UDOT (Rural)
337,192023,19,2023,9842,156,9686,3984,2.43,1868,5675,...,1931,101,114,449,535,2.13,0.67,GRAND,Rural,0 - UDOT (Rural)
379,212023,21,2023,66044,1693,64351,21467,3.00,16118,40753,...,8196,1157,345,3116,924,1.51,1.26,IRON,Rural,5 - Iron
421,232023,23,2023,12766,101,12665,3975,3.19,3871,7348,...,928,422,85,564,312,1.46,1.27,JUAB,Rural,0 - UDOT (Rural)
463,252023,25,2023,8387,168,8219,3104,2.65,1806,4473,...,2142,169,40,299,78,1.82,0.79,KANE,Rural,0 - UDOT (Rural)
505,272023,27,2023,13484,185,13299,4370,3.04,3728,7179,...,1556,1247,132,450,298,1.63,1.01,MILLARD,Rural,0 - UDOT (Rural)
547,292023,29,2023,13059,0,13059,4211,3.10,3612,7604,...,1989,447,78,796,245,1.36,1.33,MORGAN,Rural,0 - UDOT (Rural)
589,312023,31,2023,1565,0,1565,605,2.59,303,823,...,118,153,24,17,47,1.09,1.24,PIUTE,Rural,0 - UDOT (Rural)
631,332023,33,2023,2725,54,2671,958,2.79,686,1462,...,592,146,27,134,212,1.90,0.80,RICH,Rural,0 - UDOT (Rural)
673,352023,35,2023,1220554,18582,1201972,428373,2.81,272699,786677,...,273975,1249,4485,65638,29337,2.26,0.81,SALT LAKE,Urban,1 - Wasatch Front
715,372023,37,2023,14954,409,14545,5167,2.81,3655,8805,...,1101,782,358,310,341,1.30,1.31,SAN JUAN,Rural,0 - UDOT (Rural)
757,392023,39,2023,30347,2808,27539,9226,2.98,6792,19005,...,2659,1260,123,1080,574,1.50,1.38,SANPETE,Rural,0 - UDOT (Rural)
799,412023,41,2023,22164,281,21883,7586,2.88,5560,12483,...,2150,937,679,725,460,1.58,1.04,SEVIER,Rural,0 - UDOT (Rural)
841,432023,43,2023,43491,129,43362,14382,3.02,8314,26756,...,18058,883,87,3235,2534,3.17,0.59,SUMMIT,Rural,4 - Summit-Wasatch
883,452023,45,2023,79408,298,79110,24833,3.19,22072,49262,...,6398,557,260,1834,568,1.03,1.92,TOOELE,Rural,0 - UDOT (Rural)
925,472023,47,2023,36527,115,36412,12148,3.00,10050,21521,...,3805,1316,2199,1731,524,1.54,1.15,UINTAH,Rural,0 - UDOT (Rural)
967,492023,49,2023,727752,16935,710817,211379,3.36,205109,462766,...,110231,3739,857,36369,13494,1.91,1.15,UTAH,Urban,1 - Wasatch Front
1009,512023,51,2023,37933,216,37717,12556,3.00,9560,22420,...,7624,465,78,2506,1474,1.72,1.04,WASATCH,Rural,4 - Summit-Wasatch
1051,532023,53,2023,198528,3086,195442,70844,2.76,42893,109262,...,34668,710,673,12142,4858,1.62,0.95,WASHINGTON,Urban,3 - Dixie
1093,552023,55,2023,2523,0,2523,947,2.66,559,1330,...,463,181,25,259,190,2.15,0.65,WAYNE,Rural,0 - UDOT (Rural)
1135,572023,57,2023,0,0,0,0,0.00,0,0,...,0,1570,205,10740,322,inf,0.00,WEBER,Urban,1 - Wasatch Front
1220,10492023,1049,2023,3456447,56815,3399632,1142068,2.98,853666,2156409,...,607024,25118,14470,166800,71741,1.92,0.98,STATE OF UTAH,State,6 - State
1136,90572023,9057,2023,8634,121,8513,3212,2.65,2065,5378,...,992,0,0,0,75,0.84,1.99,WEBER - OGDEN VALLEY,Rural,0 - UDOT (Rural)
1178,91572023,9157,2023,261177,3652,257525,91269,2.82,62473,162681,...,37164,0,0,0,3514,1.44,1.24,WEBER - WFRC,Urban,1 - Wasatch Front