In [7]:
import pandas as pd
import numpy as np

In [8]:
se_df = pd.concat([pd.read_csv('intermediate/split_emp.csv'), pd.read_csv('intermediate/split_pop.csv')])
se_df

      CO_FIPS  YEAR VARIABLE   VALUE
0           1  2023     AGRI     730
1           1  2023     CONS     264
2           1  2023     FOOD     511
3           1  2023     GVED     750
4           1  2023      HBJ     244
...       ...   ...      ...     ...
9109     9157  2065    HHPOP  367411
9110     9157  2065       HH  164591
9111     9157  2065  POP0017   59084
9112     9157  2065  POP1864  222289
9113     9157  2065   POP65P   91658

[9482 rows x 4 columns]

In [9]:
se_df[(se_df['YEAR']==2023) & (se_df['VARIABLE']=='HH')]

      CO_FIPS  YEAR VARIABLE   VALUE
6           1  2023       HH    2280
300         5  2023       HH   44622
594         7  2023       HH    7861
888         9  2023       HH     405
1182       11  2023       HH  120087
1476       13  2023       HH    6560
1770       15  2023       HH    3756
2064       17  2023       HH    1877
2358       19  2023       HH    3984
2652       21  2023       HH   21467
2946       23  2023       HH    3975
3240       25  2023       HH    3104
3534       27  2023       HH    4370
3828       29  2023       HH    4211
4122       31  2023       HH     605
4416       33  2023       HH     958
4710       35  2023       HH  428373
5004       37  2023       HH    5167
5298       39  2023       HH    9226
5592       41  2023       HH    7586
5886       43  2023       HH   14382
6180       45  2023       HH   24833
6474       47  2023       HH   12148
6768       49  2023       HH  211379
7062       51  2023       HH   12556
7356       53  2023       HH   70844
7650       55  2023       HH     947
7944     9003  2023       HH    9191
8238     9057  2023       HH    3212
8532     9103  2023       HH   10833
8826     9157  2023       HH   91269

In [10]:
se_pivot_df = se_df.pivot(index=['CO_FIPS','YEAR'],columns='VARIABLE',values='VALUE').reset_index().fillna(0).astype(int)
se_pivot_df

VARIABLE,CO_FIPS,YEAR,AGRI,CONS,FOOD,GQPOP,GVED,HBJ,HH,HHPOP,...,MANU,MING,OFFI,OTHR,POP0017,POP1864,POP65P,RETL,TOTPOP,WSLE
0,1,2023,730,264,511,299,750,244,2280,7015,...,194,101,129,906,1942,4239,1133,485,7314,266
1,1,2025,0,0,0,369,0,0,2472,7163,...,0,0,0,0,2071,4310,1152,0,7533,0
2,1,2026,0,0,0,351,0,0,2516,7226,...,0,0,0,0,2030,4353,1194,0,7577,0
3,1,2027,0,0,0,295,0,0,2561,7287,...,0,0,0,0,1996,4363,1223,0,7582,0
4,1,2028,0,0,0,303,0,0,2600,7331,...,0,0,0,0,1971,4386,1277,0,7634,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,9157,2061,0,0,0,5406,0,0,157287,356144,...,0,0,0,0,59730,216417,85404,0,361551,0
1300,9157,2062,0,0,0,5460,0,0,159127,358961,...,0,0,0,0,59495,217801,87125,0,364421,0
1301,9157,2063,0,0,0,5513,0,0,160960,361776,...,0,0,0,0,59303,219248,88737,0,367288,0
1302,9157,2064,0,0,0,5567,0,0,162781,364591,...,0,0,0,0,59165,220852,90141,0,370158,0
1303,9157,2065,0,0,0,5622,0,0,164591,367411,...,0,0,0,0,59084,222289,91658,0,373033,0

In [12]:
se_final_df = se_pivot_df.copy()

se_final_df[';INDEX'] = se_final_df['CO_FIPS'].astype(str) + se_final_df['YEAR'].astype(str)

se_final_df['HHSIZE'] = se_final_df['HHPOP'] / se_final_df['HH']
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].replace([np.inf, -np.inf], 0)
se_final_df['HHSIZE'] = se_final_df['HHSIZE'].fillna(0).round(2)

se_final_df['ALLEMP'] = se_final_df['FOOD'] + se_final_df['MANU'] + se_final_df['WSLE'] + se_final_df['OFFI'] + se_final_df['GVED'] + se_final_df['HLTH'] + se_final_df['OTHR'] + se_final_df['AGRI'] + se_final_df['MING'] + se_final_df['CONS'] + se_final_df['HBJ']

se_final_df = se_final_df[[';INDEX','CO_FIPS','YEAR','TOTPOP','GQPOP','HHPOP','HH','HHSIZE','POP0017','POP1864','POP65P','ALLEMP','RETL','FOOD','MANU','WSLE','OFFI','GVED','HLTH','OTHR','AGRI','MING','CONS','HBJ']]
se_final_df

VARIABLE,;INDEX,CO_FIPS,YEAR,TOTPOP,GQPOP,HHPOP,HH,HHSIZE,POP0017,POP1864,...,MANU,WSLE,OFFI,GVED,HLTH,OTHR,AGRI,MING,CONS,HBJ
0,12023,1,2023,7314,299,7015,2280,3.08,1942,4239,...,194,266,129,750,148,906,730,101,264,244
1,12025,1,2025,7533,369,7163,2472,2.90,2071,4310,...,0,0,0,0,0,0,0,0,0,0
2,12026,1,2026,7577,351,7226,2516,2.87,2030,4353,...,0,0,0,0,0,0,0,0,0,0
3,12027,1,2027,7582,295,7287,2561,2.85,1996,4363,...,0,0,0,0,0,0,0,0,0,0
4,12028,1,2028,7634,303,7331,2600,2.82,1971,4386,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1299,91572061,9157,2061,361551,5406,356144,157287,2.26,59730,216417,...,0,0,0,0,0,0,0,0,0,0
1300,91572062,9157,2062,364421,5460,358961,159127,2.26,59495,217801,...,0,0,0,0,0,0,0,0,0,0
1301,91572063,9157,2063,367288,5513,361776,160960,2.25,59303,219248,...,0,0,0,0,0,0,0,0,0,0
1302,91572064,9157,2064,370158,5567,364591,162781,2.24,59165,220852,...,0,0,0,0,0,0,0,0,0,0
1303,91572065,9157,2065,373033,5622,367411,164591,2.23,59084,222289,...,0,0,0,0,0,0,0,0,0,0